spring:
  application:
    name: microservice-2

  datasource:
    url: jdbc:postgresql://postgres:5432/exampledb
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

rabbitmq:
  host: rabbitmq
  port: 5672

rest:
  template:
    service3: http://microservice-3
