
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  microservice-1:
    build:
      context: ./Microservis1/
    container_name: microservice-1
    ports:
      - "8081:8081"
    depends_on:
      - rabbitmq
    environment:
      - SPRING_PROFILES_ACTIVE=default
   
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: exampledb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - microservices-net

  microservice-2:
    build:
      context: ./Microservis2/
    container_name: microservice-2
    ports:
      - "8082:8082"
    depends_on:
      - rabbitmq
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: default
  
  microservice-3:
    build:
      context: ./Microservis3/
    ports:
      - "8083:8083"
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge



